### ISSUE TITLE
Inactive space on the left when dragging

### ISSUE THREAD

**Issue by NeXTs** [asmyshlyaev177/react-horizontal-scrolling-menu#41]
[Example on codesandbox](https://codesandbox.io/s/pk9k31npj7)

There is some inactive space on the left, when dragging items.
When you drag to the right - it scrolls back to the center, as intended.
Same happens when you scroll way left, it scrolls back to the center, it's ok.
But when you scroll slightly to the left, there is an area where items stuck and do not scrolls back to the center.

![bug3](https://user-images.githubusercontent.com/1753208/52960528-aefbce80-33a1-11e9-813b-d9a3ddfa9d46.gif)

**Comment by asmyshlyaev177** [comment]
Didn't intend to work like this.
Will try to add this feature later.

**Comment by marcinWojciechowskiLingaro** [comment]
+1, transform: translate3d() adds useless spacing on the left and right

**Comment by asmyshlyaev177** [comment]
I fixed it, should work fine in version 0.5.5 .

**Comment by NeXTs** [comment]
Hey
Yes, in version 0.5.5 there is no more inactive space, but #40 bug appears again

**Comment by asmyshlyaev177** [comment]
Strange, can't reproduce it now, but should be bug only in example project.

**Comment by marcinWojciechowskiLingaro** [comment]
Still can't remove this spacing.

![image](https://user-images.githubusercontent.com/47417125/54155519-946ac180-4444-11e9-95cc-7013002a5d8b.png)

**Comment by asmyshlyaev177** [comment]
Can you reproduce it?

**Comment by asmyshlyaev177** [comment]
I guess i see it.

**Comment by marcinWojciechowskiLingaro** [comment]
> Will be good if you can reproduce it.

![image](https://user-images.githubusercontent.com/47417125/54156523-b9f8ca80-4446-11e9-9092-9d429d9cab0d.png)

Something is wrong with first and last item in calculations. For first one should be 0px, 0px, 0px and it would be working fine.

**Comment by asmyshlyaev177** [comment]
Maybe something else, it is 0 if alignCenter = false.

**Comment by marcinWojciechowskiLingaro** [comment]
Yes now it works, but now I possibility to review previous item from the left. Any idea how to make item3 visible? To improve UX?

![image](https://user-images.githubusercontent.com/47417125/54157326-61c2c800-4448-11e9-93bf-3c214e28d6e1.png)

**Comment by asmyshlyaev177** [comment]
Only show arrow, not sure.

**Comment by NeXTs** [comment]
> Strange, can't reproduce it now, but should be bug only in example project.

https://codesandbox.io/s/l207m799kq

**Comment by asmyshlyaev177** [comment]
Thank you, fixed it, check 0.5.6 version.

**Comment by NeXTs** [comment]
Yes, it works great now. Thank you!

**Comment by NeXTs** [comment]
> Still can't remove this spacing.
> 
> ![image](https://user-images.githubusercontent.com/47417125/54155519-946ac180-4444-11e9-95cc-7013002a5d8b.png)

In version 0.5.6 I've faced this problem too. Appears on init.
Settings 

```
<ScrollMenu
  data={this.items}
  arrowLeft={<Arrow type="prev" className={style.sliderArrow} />}
  arrowRight={<Arrow type="next" className={style.sliderArrow} />}
  onSelect={this.onItemClick}
  wheel={false}
  alignCenter={false}
  wrapperClass={style.sliderInner}
  itemClass={style.sliderItem}
/>
```

**Comment by NeXTs** [comment]
Do you need some demo to reproduce this or you've already noticed this behavior too?

**Comment by asmyshlyaev177** [comment]
Better if have demo.

**Comment by NeXTs** [comment]
@marcinWojciechowskiLingaro do you have any?

**Comment by NeXTs** [comment]
I've reinstalled whole node_modules and don't see this issue anymore.
